import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1777017484499 implements MigrationInterface {
    name = 'InitSchema1777017484499'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "username" character varying(100) NOT NULL, "google_id" character varying(255), "avatar_url" character varying(500), "password_hash" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0bd5012aeb82628e07f6a1be53" ON "users" ("google_id") `);
        await queryRunner.query(`CREATE TABLE "user_workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "user_id" uuid NOT NULL, "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_opened_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3c26b2f35801149e8f0af2e4fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_user_workspaces_workspace_id" ON "user_workspaces" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_workspaces_user_id" ON "user_workspaces" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_user_workspaces_workspace_user" ON "user_workspaces" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."workspaces_plan_type_enum" AS ENUM('free', 'pro')`);
        await queryRunner.query(`CREATE TABLE "workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "plan_type" "public"."workspaces_plan_type_enum" NOT NULL DEFAULT 'free', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_b8e9fe62e93d60089dfc4f175f3" UNIQUE ("slug"), CONSTRAINT "PK_098656ae401f3e1a4586f47fd8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "task_priorities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "level" integer NOT NULL, "color" character varying(30), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa148974939142ee75716ee34e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8a5da24ee33550e6a8b36d960a" ON "task_priorities" ("project_id", "level") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0b8db587f3fa0723369398ac37" ON "task_priorities" ("project_id", "name") `);
        await queryRunner.query(`CREATE TABLE "task_statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "position" integer NOT NULL DEFAULT '0', "color" character varying(30), "is_done" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28fe920c04b1baa795d82773739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abd81daad5031170fd80eb270d" ON "task_statuses" ("project_id", "name") `);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "sprint_id" uuid, "project_seq" integer, "title" character varying(255) NOT NULL, "description" text, "status_id" uuid NOT NULL, "priority_id" uuid, "reporter_id" uuid NOT NULL, "assignee_id" uuid, "start_at" TIMESTAMP, "due_at" TIMESTAMP, "completed_at" TIMESTAMP, "estimate_minutes" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_SPRINT_ID" ON "tasks" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_ASSIGNEE_ID" ON "tasks" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_CREATED_BY" ON "tasks" ("reporter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_PRIORITY_ID" ON "tasks" ("priority_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_STATUS_ID" ON "tasks" ("status_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_PROJECT_ID" ON "tasks" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_WORKSPACE_ID" ON "tasks" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_TASKS_PROJECT_SEQ" ON "tasks" ("project_id", "project_seq") `);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "goal" character varying(500), "start_at" TIMESTAMP, "end_at" TIMESTAMP, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_82145010051f3f2fc94671c0b3" ON "sprints" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8377d578af0d41c855635574dd" ON "sprints" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_visibility_enum" AS ENUM('PRIVATE', 'INTERNAL')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "key" character varying(50) NOT NULL, "visibility" "public"."projects_visibility_enum" NOT NULL DEFAULT 'PRIVATE', "task_seq" integer NOT NULL DEFAULT '0', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PROJECTS_WORKSPACE_ID" ON "projects" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PROJECTS_WORKSPACE_KEY" ON "projects" ("workspace_id", "key") `);
        await queryRunner.query(`CREATE TYPE "public"."boards_view_type_enum" AS ENUM('BOARD', 'TABLE', 'LIST', 'CALENDAR', 'TIMELINE', 'GALLERY', 'CHART', 'DASHBOARD', 'FORM', 'MAP', 'FEED')`);
        await queryRunner.query(`CREATE TABLE "boards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "view_type" "public"."boards_view_type_enum" NOT NULL DEFAULT 'BOARD', "created_by" uuid NOT NULL, "updated_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_606923b0b068ef262dfdcd18f44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_BOARDS_PROJECT_NAME" ON "boards" ("project_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOARDS_PROJECT_ID" ON "boards" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOARDS_WORKSPACE_ID" ON "boards" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."page_blocks_type_enum" AS ENUM('TEXT', 'HEADER', 'QUOTE', 'DIVIDER', 'CODE', 'TODO', 'IMAGE', 'VIDEO', 'FILE', 'BOOKMARK', 'EMBED', 'FIGMA', 'GITHUB_GIST', 'GOOGLE_MAPS', 'TWEET', 'DATABASE_VIEW', 'TABLE_SIMPLE', 'MERMAID', 'BUTTON')`);
        await queryRunner.query(`CREATE TABLE "page_blocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "page_id" uuid NOT NULL, "type" "public"."page_blocks_type_enum" NOT NULL, "title" character varying, "order_index" integer NOT NULL DEFAULT '0', "position_x" integer, "position_y" integer, "width" integer, "height" integer, "content" jsonb, "data_config" jsonb, "style_config" jsonb, "created_by" uuid NOT NULL, "is_open" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_da57feac0f4c851a6419487176b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PAGE_BLOCKS_PAGE_ORDER" ON "page_blocks" ("page_id", "order_index") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAGE_BLOCKS_PAGE_ID" ON "page_blocks" ("page_id") `);
        await queryRunner.query(`CREATE TABLE "pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255), "is_template" boolean NOT NULL DEFAULT false, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PAGES_WORKSPACE_SLUG" ON "pages" ("workspace_id", "slug") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAGES_WORKSPACE_ID" ON "pages" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying(512) NOT NULL, "user_agent" character varying(255), "ip_address" inet, "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_token_user" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_token_token" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('OWNER', 'MEMBER', 'ADMIN')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_role_workspace_name" ON "roles" ("workspace_id", "name") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_permission" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_role" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "role_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" uuid, CONSTRAINT "PK_3868a216bfe72626b8b80e1dc4f" PRIMARY KEY ("user_id", "workspace_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_workspace_user" ON "user_roles" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_type_enum" AS ENUM('EMAIL', 'LINK')`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_role_name_enum" AS ENUM('OWNER', 'MEMBER', 'ADMIN')`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "workspace_invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "user_id" uuid, "email" character varying(255), "type" "public"."workspace_invites_type_enum" NOT NULL DEFAULT 'EMAIL', "role_name" "public"."workspace_invites_role_name_enum" NOT NULL DEFAULT 'MEMBER', "invited_by" uuid NOT NULL, "token" character varying(255) NOT NULL, "status" "public"."workspace_invites_status_enum" NOT NULL DEFAULT 'PENDING', "accepted_at" TIMESTAMP, "expires_at" TIMESTAMP NOT NULL, "max_uses" integer, "used_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43f7a0e0b0549fe2581e9cb57bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_type" ON "workspace_invites" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_user_id" ON "workspace_invites" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_invited_by" ON "workspace_invites" ("invited_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_status" ON "workspace_invites" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_email" ON "workspace_invites" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_workspace_id" ON "workspace_invites" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_workspace_invites_token" ON "workspace_invites" ("token") `);
        await queryRunner.query(`ALTER TABLE "user_workspaces" ADD CONSTRAINT "FK_b2c27397c6389ce190d492d30da" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" ADD CONSTRAINT "FK_87fe6693df535a622eaf4248697" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_priorities" ADD CONSTRAINT "FK_9f5351226f12f052b9da79af93f" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_priorities" ADD CONSTRAINT "FK_90cb292b1088ae8027d5843edef" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_statuses" ADD CONSTRAINT "FK_5306f541f83255c6c0ca251189f" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_statuses" ADD CONSTRAINT "FK_1918c92dc3fb9fd3b0df2e6a7e4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_5cb6ca4667dfa947871694da959" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b512d5a489d692f66569978b8a7" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e28288969fa7827bd12680cfe10" FOREIGN KEY ("status_id") REFERENCES "task_statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_5d1c8f7898b5b84ad5ce08fcff8" FOREIGN KEY ("priority_id") REFERENCES "task_priorities"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_855d484825b715c545349212c7f" FOREIGN KEY ("assignee_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_8377d578af0d41c855635574ddd" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_bf217cf96eaeb253a7cd35b52ad" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_1542ae826c0dfeaf4c79e07fc57" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_8156e1b3bd94cb1812a6d55375c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_983b7eec43b4188489af2981a0e" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_blocks" ADD CONSTRAINT "FK_ad019765c7ffab9084d1d215d48" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_blocks" ADD CONSTRAINT "FK_c04e1bba3158ed15a30eee0349c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_e81517e2f307170573c9be6f581" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_064ab67bb29a28d073db287fc6d" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_5291e7ee78e540217bd44bd3688" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_4cd2a0a1566d9ddcab3068ac642" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ADD CONSTRAINT "FK_9ffc4e5b893e8fb91d66d466f6d" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ADD CONSTRAINT "FK_93d8174e8b1537da7b092621c7f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ADD CONSTRAINT "FK_cf390e54ae1d8871cb74aad9c89" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workspace_invites" DROP CONSTRAINT "FK_cf390e54ae1d8871cb74aad9c89"`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" DROP CONSTRAINT "FK_93d8174e8b1537da7b092621c7f"`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" DROP CONSTRAINT "FK_9ffc4e5b893e8fb91d66d466f6d"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_4cd2a0a1566d9ddcab3068ac642"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_5291e7ee78e540217bd44bd3688"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_064ab67bb29a28d073db287fc6d"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_e81517e2f307170573c9be6f581"`);
        await queryRunner.query(`ALTER TABLE "page_blocks" DROP CONSTRAINT "FK_c04e1bba3158ed15a30eee0349c"`);
        await queryRunner.query(`ALTER TABLE "page_blocks" DROP CONSTRAINT "FK_ad019765c7ffab9084d1d215d48"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_983b7eec43b4188489af2981a0e"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_8156e1b3bd94cb1812a6d55375c"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_1542ae826c0dfeaf4c79e07fc57"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_bf217cf96eaeb253a7cd35b52ad"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_8377d578af0d41c855635574ddd"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_855d484825b715c545349212c7f"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_5d1c8f7898b5b84ad5ce08fcff8"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e28288969fa7827bd12680cfe10"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b512d5a489d692f66569978b8a7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_5cb6ca4667dfa947871694da959"`);
        await queryRunner.query(`ALTER TABLE "task_statuses" DROP CONSTRAINT "FK_1918c92dc3fb9fd3b0df2e6a7e4"`);
        await queryRunner.query(`ALTER TABLE "task_statuses" DROP CONSTRAINT "FK_5306f541f83255c6c0ca251189f"`);
        await queryRunner.query(`ALTER TABLE "task_priorities" DROP CONSTRAINT "FK_90cb292b1088ae8027d5843edef"`);
        await queryRunner.query(`ALTER TABLE "task_priorities" DROP CONSTRAINT "FK_9f5351226f12f052b9da79af93f"`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" DROP CONSTRAINT "FK_87fe6693df535a622eaf4248697"`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" DROP CONSTRAINT "FK_b2c27397c6389ce190d492d30da"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_workspace_invites_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_invited_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_type"`);
        await queryRunner.query(`DROP TABLE "workspace_invites"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_role_name_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_workspace_user"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_permission"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_role_workspace_name"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_token_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_token_user"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAGES_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PAGES_WORKSPACE_SLUG"`);
        await queryRunner.query(`DROP TABLE "pages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAGE_BLOCKS_PAGE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PAGE_BLOCKS_PAGE_ORDER"`);
        await queryRunner.query(`DROP TABLE "page_blocks"`);
        await queryRunner.query(`DROP TYPE "public"."page_blocks_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOARDS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOARDS_PROJECT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_BOARDS_PROJECT_NAME"`);
        await queryRunner.query(`DROP TABLE "boards"`);
        await queryRunner.query(`DROP TYPE "public"."boards_view_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PROJECTS_WORKSPACE_KEY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROJECTS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_visibility_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8377d578af0d41c855635574dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82145010051f3f2fc94671c0b3"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_TASKS_PROJECT_SEQ"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_PROJECT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_STATUS_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_PRIORITY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_CREATED_BY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_ASSIGNEE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_SPRINT_ID"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abd81daad5031170fd80eb270d"`);
        await queryRunner.query(`DROP TABLE "task_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b8db587f3fa0723369398ac37"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a5da24ee33550e6a8b36d960a"`);
        await queryRunner.query(`DROP TABLE "task_priorities"`);
        await queryRunner.query(`DROP TABLE "workspaces"`);
        await queryRunner.query(`DROP TYPE "public"."workspaces_plan_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_user_workspaces_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_workspaces_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_workspaces_workspace_id"`);
        await queryRunner.query(`DROP TABLE "user_workspaces"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bd5012aeb82628e07f6a1be53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
