import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1778254830281 implements MigrationInterface {
    name = 'InitSchema1778254830281'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."activities_entity_type_enum" AS ENUM('TASK', 'SPRINT', 'COMMENT', 'ATTACHMENT', 'PAGE', 'PAGE_BLOCK', 'WORKSPACE', 'PROJECT')`);
        await queryRunner.query(`CREATE TYPE "public"."activities_action_enum" AS ENUM('TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_RESTORED', 'TASK_STATUS_CHANGED', 'TASK_PRIORITY_CHANGED', 'TASK_TITLE_CHANGED', 'TASK_DESCRIPTION_CHANGED', 'TASK_DUE_DATE_CHANGED', 'TASK_START_DATE_CHANGED', 'TASK_ESTIMATE_CHANGED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_MOVED_TO_SPRINT', 'TASK_REMOVED_FROM_SPRINT', 'TASK_MOVED_TO_BACKLOG', 'SPRINT_CREATED', 'SPRINT_UPDATED', 'SPRINT_STARTED', 'SPRINT_COMPLETED', 'SPRINT_CANCELLED', 'SPRINT_DELETED', 'SPRINT_RESTORED', 'COMMENT_CREATED', 'COMMENT_UPDATED', 'COMMENT_DELETED', 'ATTACHMENT_UPLOADED', 'ATTACHMENT_DELETED', 'PAGE_CREATED', 'PAGE_UPDATED', 'PAGE_DELETED', 'PAGE_RESTORED', 'PAGE_BLOCK_CREATED', 'PAGE_BLOCK_UPDATED', 'PAGE_BLOCK_DELETED', 'PAGE_BLOCK_REORDERED', 'WORKSPACE_MEMBER_JOINED', 'WORKSPACE_MEMBER_REMOVED', 'WORKSPACE_MEMBER_ROLE_CHANGED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_RESTORED')`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid, "entity_type" "public"."activities_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "actor_id" uuid, "action" "public"."activities_action_enum" NOT NULL, "field" character varying(100), "old_value" jsonb, "new_value" jsonb, "metadata" jsonb, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78e06b2e7a3bd9b9239de4aa28" ON "activities" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_789eee36df14bb2a655b087404" ON "activities" ("workspace_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bca646bf128e29d7b1f5fd2339" ON "activities" ("workspace_id", "project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_70f034bc5912fde02b82b329f1" ON "activities" ("workspace_id", "entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entity_type_enum" AS ENUM('WORKSPACE', 'PROJECT', 'TASK', 'SPRINT', 'COMMENT', 'ATTACHMENT', 'PAGE', 'PAGE_BLOCK', 'USER', 'ROLE', 'PERMISSION', 'BILLING', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid, "actor_id" uuid, "action" character varying(150) NOT NULL, "entity_type" "public"."audit_logs_entity_type_enum", "entity_id" uuid, "before_value" jsonb, "after_value" jsonb, "metadata" jsonb, "ip_address" character varying(100), "user_agent" text, "request_id" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_959054ba1c3ad6190ce3f7c754" ON "audit_logs" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e140f8ddef870ea93925f251f2" ON "audit_logs" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."billing_webhooks_provider_enum" AS ENUM('MANUAL', 'VISA', 'MOMO', 'VNPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."billing_webhooks_status_enum" AS ENUM('RECEIVED', 'PROCESSED', 'FAILED', 'IGNORED')`);
        await queryRunner.query(`CREATE TABLE "billing_webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "provider" "public"."billing_webhooks_provider_enum" NOT NULL, "provider_event_id" character varying(255) NOT NULL, "event_type" character varying(255) NOT NULL, "status" "public"."billing_webhooks_status_enum" NOT NULL DEFAULT 'RECEIVED', "payload" jsonb NOT NULL, "processed_at" TIMESTAMP, "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed6e913d220f1564d85f68584b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a809bf2073f818f5598870ca47" ON "billing_webhooks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a679b0c06c3447bce6b9b221a2" ON "billing_webhooks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae20f0cef30a0636299478d3b9" ON "billing_webhooks" ("event_type") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2f7b512cb530d7ecbf1bc11140" ON "billing_webhooks" ("provider", "provider_event_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "subscription_id" uuid, "invoice_number" character varying(100) NOT NULL, "amount_due" integer NOT NULL DEFAULT '0', "amount_paid" integer NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'OPEN', "hosted_invoice_url" text, "invoice_pdf_url" text, "due_at" TIMESTAMP, "paid_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_d8f8d3788694e1b3f96c42c36fb" UNIQUE ("invoice_number"), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_5152c0aa0f851d9b95972b442e" ON "invoices" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_029d141be7ee764c2465186539" ON "invoices" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('MANUAL', 'VISA', 'MOMO', 'VNPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "subscription_id" uuid, "invoice_id" uuid, "provider" "public"."payments_provider_enum" NOT NULL DEFAULT 'MANUAL', "provider_payment_id" character varying(255), "amount" integer NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'VND', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "paid_at" TIMESTAMP, "failed_reason" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_66e758f1718149c6d39f94d351" ON "payments" ("provider", "provider_payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_75848dfef07fd19027e08ca81d" ON "payments" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ccd725eebd8cb880344f32a51a" ON "payments" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."plans_billing_interval_enum" AS ENUM('MONTH', 'YEAR', 'LIFETIME')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, "price_amount" integer NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "billing_interval" "public"."plans_billing_interval_enum" NOT NULL DEFAULT 'MONTH', "features" jsonb, "limits" jsonb, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "UQ_e7b71bb444e74ee067df057397e" UNIQUE ("slug"), CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ac30ab7d4ef974259069a8750" ON "plans" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e7b71bb444e74ee067df057397" ON "plans" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."usage_limits_resource_type_enum" AS ENUM('MEMBERS', 'PROJECTS', 'TASKS', 'PAGES', 'PAGE_TEMPLATES', 'STORAGE_MB', 'ATTACHMENTS', 'SPRINTS')`);
        await queryRunner.query(`CREATE TABLE "usage_limits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "plan_id" uuid, "resource_type" "public"."usage_limits_resource_type_enum" NOT NULL, "limit_value" integer, "used_value" integer NOT NULL DEFAULT '0', "reset_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd1b4a9985764deab5c86fe23d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_176541ede12e93282f7d3001f5" ON "usage_limits" ("plan_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_181e10fb568e8abc0f9fa80198" ON "usage_limits" ("workspace_id", "resource_type") `);
        await queryRunner.query(`CREATE TYPE "public"."mentions_source_type_enum" AS ENUM('TASK_COMMENT', 'PAGE_COMMENT', 'PAGE_BLOCK')`);
        await queryRunner.query(`CREATE TYPE "public"."mentions_entity_type_enum" AS ENUM('TASK', 'PAGE', 'PAGE_BLOCK')`);
        await queryRunner.query(`CREATE TABLE "mentions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid, "mentioner_id" uuid NOT NULL, "mentioned_user_id" uuid NOT NULL, "source_type" "public"."mentions_source_type_enum" NOT NULL, "source_id" uuid NOT NULL, "entity_type" "public"."mentions_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "notification_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c728c4685beaa7be19e11eae42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08cc326bcc36b69774c6721e9a" ON "mentions" ("notification_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d644737df1052524a913770615" ON "mentions" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa0f2f3576ba3faf0607be6445" ON "mentions" ("workspace_id", "source_type", "source_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d7917a734629d1cc15887086" ON "mentions" ("workspace_id", "mentioned_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_COMMENTED', 'TASK_MENTIONED', 'TASK_DUE_SOON', 'WORKSPACE_INVITED', 'WORKSPACE_MEMBER_JOINED', 'SPRINT_STARTED', 'SPRINT_COMPLETED', 'PAGE_MENTIONED', 'PAGE_SHARED', 'SYSTEM')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_entity_type_enum" AS ENUM('TASK', 'SPRINT', 'COMMENT', 'PAGE', 'WORKSPACE', 'PROJECT', 'INVITE')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid, "user_id" uuid NOT NULL, "actor_id" uuid, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text, "entity_type" "public"."notifications_entity_type_enum", "entity_id" uuid, "metadata" jsonb, "read_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_d5ace4f24abe554acb1a919656" ON "notifications" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8385e7e4b0c91cfa308cba3f13" ON "notifications" ("workspace_id", "user_id", "read_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_91fa0aebab77f3ac7568a364da" ON "notifications" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "page_template_blocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "template_id" uuid NOT NULL, "parent_block_id" uuid, "type" character varying(100) NOT NULL, "content" jsonb, "order_index" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_6c101f8b441c5979cb276c4878c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_447c6640293687c7b23aa847e1" ON "page_template_blocks" ("parent_block_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1589dbc502d1c94df485cd6a58" ON "page_template_blocks" ("template_id", "order_index") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bcdeb9feaeaf76b2b12dcd63d" ON "page_template_blocks" ("template_id") `);
        await queryRunner.query(`CREATE TABLE "page_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid, "name" character varying(255) NOT NULL, "description" text, "icon" character varying(100), "cover_url" text, "category" character varying(100), "is_system" boolean NOT NULL DEFAULT false, "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f6263e9e28902172839e84b554b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_58bb1789bf717565065285da1a" ON "page_templates" ("is_system") `);
        await queryRunner.query(`CREATE INDEX "IDX_de38328ab305acccaca02ba3bd" ON "page_templates" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_183935f53af20e942d693e2b44" ON "page_templates" ("workspace_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7ae07a4b119fa5660e081fb07" ON "page_templates" ("workspace_id") `);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP INDEX "public"."IDX_c7ae07a4b119fa5660e081fb07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_183935f53af20e942d693e2b44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de38328ab305acccaca02ba3bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58bb1789bf717565065285da1a"`);
        await queryRunner.query(`DROP TABLE "page_templates"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bcdeb9feaeaf76b2b12dcd63d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1589dbc502d1c94df485cd6a58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_447c6640293687c7b23aa847e1"`);
        await queryRunner.query(`DROP TABLE "page_template_blocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_91fa0aebab77f3ac7568a364da"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8385e7e4b0c91cfa308cba3f13"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d5ace4f24abe554acb1a919656"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47d7917a734629d1cc15887086"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa0f2f3576ba3faf0607be6445"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d644737df1052524a913770615"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08cc326bcc36b69774c6721e9a"`);
        await queryRunner.query(`DROP TABLE "mentions"`);
        await queryRunner.query(`DROP TYPE "public"."mentions_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."mentions_source_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_181e10fb568e8abc0f9fa80198"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_176541ede12e93282f7d3001f5"`);
        await queryRunner.query(`DROP TABLE "usage_limits"`);
        await queryRunner.query(`DROP TYPE "public"."usage_limits_resource_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7b71bb444e74ee067df057397"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ac30ab7d4ef974259069a8750"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_billing_interval_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ccd725eebd8cb880344f32a51a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75848dfef07fd19027e08ca81d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66e758f1718149c6d39f94d351"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_029d141be7ee764c2465186539"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5152c0aa0f851d9b95972b442e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f7b512cb530d7ecbf1bc11140"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae20f0cef30a0636299478d3b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a679b0c06c3447bce6b9b221a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a809bf2073f818f5598870ca47"`);
        await queryRunner.query(`DROP TABLE "billing_webhooks"`);
        await queryRunner.query(`DROP TYPE "public"."billing_webhooks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."billing_webhooks_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e140f8ddef870ea93925f251f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177183f29f438c488b5e8510cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_959054ba1c3ad6190ce3f7c754"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70f034bc5912fde02b82b329f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bca646bf128e29d7b1f5fd2339"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_789eee36df14bb2a655b087404"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78e06b2e7a3bd9b9239de4aa28"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TYPE "public"."activities_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activities_entity_type_enum"`);
    }

}
