import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1781444336710 implements MigrationInterface {
    name = 'InitSchema1781444336710'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."activities_entity_type_enum" AS ENUM('TASK', 'SPRINT', 'COMMENT', 'ATTACHMENT', 'PAGE', 'PAGE_BLOCK', 'WORKSPACE', 'PROJECT')`);
        await queryRunner.query(`CREATE TYPE "public"."activities_action_enum" AS ENUM('TASK_CREATED', 'TASK_UPDATED', 'TASK_DELETED', 'TASK_RESTORED', 'TASK_STATUS_CHANGED', 'TASK_PRIORITY_CHANGED', 'TASK_TITLE_CHANGED', 'TASK_DESCRIPTION_CHANGED', 'TASK_DUE_DATE_CHANGED', 'TASK_START_DATE_CHANGED', 'TASK_ESTIMATE_CHANGED', 'TASK_ASSIGNED', 'TASK_UNASSIGNED', 'TASK_MOVED_TO_SPRINT', 'TASK_REMOVED_FROM_SPRINT', 'TASK_MOVED_TO_BACKLOG', 'SPRINT_CREATED', 'SPRINT_UPDATED', 'SPRINT_STARTED', 'SPRINT_COMPLETED', 'SPRINT_CANCELLED', 'SPRINT_DELETED', 'SPRINT_RESTORED', 'COMMENT_CREATED', 'COMMENT_UPDATED', 'COMMENT_DELETED', 'ATTACHMENT_UPLOADED', 'ATTACHMENT_DELETED', 'PAGE_CREATED', 'PAGE_UPDATED', 'PAGE_DELETED', 'PAGE_RESTORED', 'PAGE_BLOCK_CREATED', 'PAGE_BLOCK_UPDATED', 'PAGE_BLOCK_DELETED', 'PAGE_BLOCK_REORDERED', 'WORKSPACE_MEMBER_JOINED', 'WORKSPACE_MEMBER_REMOVED', 'WORKSPACE_MEMBER_ROLE_CHANGED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'PROJECT_DELETED', 'PROJECT_RESTORED')`);
        await queryRunner.query(`CREATE TABLE "activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid, "entity_type" "public"."activities_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "actor_id" uuid, "action" "public"."activities_action_enum" NOT NULL, "field" character varying(100), "old_value" jsonb, "new_value" jsonb, "metadata" jsonb, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7f4004429f731ffb9c88eb486a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_78e06b2e7a3bd9b9239de4aa28" ON "activities" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_789eee36df14bb2a655b087404" ON "activities" ("workspace_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_bca646bf128e29d7b1f5fd2339" ON "activities" ("workspace_id", "project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_70f034bc5912fde02b82b329f1" ON "activities" ("workspace_id", "entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."attachments_provider_enum" AS ENUM('R2', 'CLOUDINARY')`);
        await queryRunner.query(`CREATE TYPE "public"."attachments_status_enum" AS ENUM('READY', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "attachments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "task_id" uuid, "comment_id" uuid, "uploaded_by" uuid NOT NULL, "file_name" character varying(255) NOT NULL, "mime_type" character varying(150) NOT NULL, "size" bigint NOT NULL, "provider" "public"."attachments_provider_enum" NOT NULL DEFAULT 'R2', "storage_key" text, "public_id" text, "url" text, "secure_url" text, "status" "public"."attachments_status_enum" NOT NULL DEFAULT 'READY', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5e1f050bcff31e3084a1d662412" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_3fb5314ef323d02aed62ccb283" ON "attachments" ("public_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ec3648b85f6af7eafe865a3257" ON "attachments" ("storage_key") `);
        await queryRunner.query(`CREATE INDEX "IDX_7eb55326eb220fef58d00cccbf" ON "attachments" ("workspace_id", "comment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_244c5f17089416157f6dc9190f" ON "attachments" ("workspace_id", "task_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_entity_type_enum" AS ENUM('WORKSPACE', 'PROJECT', 'TASK', 'SPRINT', 'COMMENT', 'ATTACHMENT', 'PAGE', 'PAGE_BLOCK', 'USER', 'ROLE', 'PERMISSION', 'BILLING', 'SYSTEM')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid, "actor_id" uuid, "action" character varying(150) NOT NULL, "entity_type" "public"."audit_logs_entity_type_enum", "entity_id" uuid, "before_value" jsonb, "after_value" jsonb, "metadata" jsonb, "ip_address" character varying(100), "user_agent" text, "request_id" character varying(100), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_959054ba1c3ad6190ce3f7c754" ON "audit_logs" ("request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e140f8ddef870ea93925f251f2" ON "audit_logs" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "user_profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "display_name" character varying(150), "full_name" character varying(150), "bio" text, "phone_number" character varying(30), "location" character varying(150), "job_title" character varying(150), "website" character varying(255), "cover_url" character varying(500), "timezone" character varying(50), "language" character varying(20), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_6ca9503d77ae39b4b5a6cc3ba88" UNIQUE ("user_id"), CONSTRAINT "REL_6ca9503d77ae39b4b5a6cc3ba8" UNIQUE ("user_id"), CONSTRAINT "PK_1ec6662219f4605723f1e41b6cb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_system_role_enum" AS ENUM('USER', 'SYSTEM_ADMIN', 'SUPER_ADMIN')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "username" character varying(100) NOT NULL, "google_id" character varying(255), "avatar_url" character varying(500), "password_hash" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "is_email_verified" boolean NOT NULL DEFAULT false, "email_verification_token" character varying(255), "email_verification_expires" TIMESTAMP, "reset_password_token" character varying(255), "reset_password_expires" TIMESTAMP, "system_role" "public"."users_system_role_enum" NOT NULL DEFAULT 'USER', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe0bb3f6520ee0469504521e71" ON "users" ("username") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0bd5012aeb82628e07f6a1be53" ON "users" ("google_id") `);
        await queryRunner.query(`CREATE TYPE "public"."boards_view_type_enum" AS ENUM('BOARD', 'TABLE', 'LIST', 'CALENDAR', 'TIMELINE', 'GALLERY', 'CHART', 'DASHBOARD', 'FORM', 'MAP', 'FEED', 'BACKLOG')`);
        await queryRunner.query(`CREATE TABLE "boards" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "view_type" "public"."boards_view_type_enum" NOT NULL DEFAULT 'BOARD', "created_by" uuid NOT NULL, "updated_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "PK_606923b0b068ef262dfdcd18f44" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_BOARDS_PROJECT_NAME_ACTIVE" ON "boards" ("project_id", "name") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_BOARDS_DELETED_AT" ON "boards" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOARDS_PROJECT_ID" ON "boards" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_BOARDS_WORKSPACE_ID" ON "boards" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "task_assignees" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "task_id" uuid NOT NULL, "user_id" uuid NOT NULL, "assigned_by" uuid, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_e23bc1438f7bb32f41e8d493e78" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_ASSIGNEES_ASSIGNED_BY" ON "task_assignees" ("assigned_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_ASSIGNEES_USER_ID" ON "task_assignees" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_ASSIGNEES_TASK_ID" ON "task_assignees" ("task_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_TASK_ASSIGNEES_TASK_USER" ON "task_assignees" ("task_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "task_priorities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "level" integer NOT NULL, "color" character varying(30), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_aa148974939142ee75716ee34e3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_8a5da24ee33550e6a8b36d960a" ON "task_priorities" ("project_id", "level") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0b8db587f3fa0723369398ac37" ON "task_priorities" ("project_id", "name") `);
        await queryRunner.query(`CREATE TABLE "task_statuses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(100) NOT NULL, "position" integer NOT NULL DEFAULT '0', "color" character varying(30), "is_done" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_28fe920c04b1baa795d82773739" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abd81daad5031170fd80eb270d" ON "task_statuses" ("project_id", "name") `);
        await queryRunner.query(`CREATE TABLE "tasks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "sprint_id" uuid, "project_seq" integer, "title" character varying(255) NOT NULL, "description" text, "status_id" uuid NOT NULL, "priority_id" uuid, "reporter_id" uuid NOT NULL, "start_at" TIMESTAMP, "due_at" TIMESTAMP, "completed_at" TIMESTAMP, "estimate_minutes" integer, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "PK_8d12ff38fcc62aaba2cab748772" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_DELETED_AT" ON "tasks" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_SPRINT_ID" ON "tasks" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_CREATED_BY" ON "tasks" ("reporter_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_PRIORITY_ID" ON "tasks" ("priority_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_STATUS_ID" ON "tasks" ("status_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_PROJECT_ID" ON "tasks" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASKS_WORKSPACE_ID" ON "tasks" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_TASKS_PROJECT_SEQ" ON "tasks" ("project_id", "project_seq") `);
        await queryRunner.query(`CREATE TYPE "public"."sprints_status_enum" AS ENUM('PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED')`);
        await queryRunner.query(`CREATE TABLE "sprints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "goal" character varying(500), "status" "public"."sprints_status_enum" NOT NULL DEFAULT 'PLANNED', "start_at" TIMESTAMP, "end_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "PK_6800aa2e0f508561812c4b9afb4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_SPRINTS_PROJECT_NAME_ACTIVE" ON "sprints" ("project_id", "name") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_SPRINTS_DELETED_AT" ON "sprints" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_507d36b62bcb05326a1afb3e88" ON "sprints" ("workspace_id", "project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_82145010051f3f2fc94671c0b3" ON "sprints" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8377d578af0d41c855635574dd" ON "sprints" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."projects_visibility_enum" AS ENUM('PRIVATE', 'INTERNAL')`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "name" character varying(255) NOT NULL, "key" character varying(50) NOT NULL, "visibility" "public"."projects_visibility_enum" NOT NULL DEFAULT 'PRIVATE', "task_seq" integer NOT NULL DEFAULT '0', "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_PROJECTS_DELETED_AT" ON "projects" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_PROJECTS_WORKSPACE_ID" ON "projects" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PROJECTS_WORKSPACE_KEY_ACTIVE" ON "projects" ("workspace_id", "key") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE TABLE "user_workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "user_id" uuid NOT NULL, "joined_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_opened_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_3c26b2f35801149e8f0af2e4fb0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_user_workspaces_workspace_id" ON "user_workspaces" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_workspaces_user_id" ON "user_workspaces" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_user_workspaces_workspace_user" ON "user_workspaces" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."workspaces_plan_type_enum" AS ENUM('free', 'pro')`);
        await queryRunner.query(`CREATE TYPE "public"."workspaces_layout_mode_enum" AS ENUM('tabs', 'blocks')`);
        await queryRunner.query(`CREATE TABLE "workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "slug" character varying(255) NOT NULL, "plan_type" "public"."workspaces_plan_type_enum" NOT NULL DEFAULT 'free', "layout_mode" "public"."workspaces_layout_mode_enum" NOT NULL DEFAULT 'tabs', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "UQ_b8e9fe62e93d60089dfc4f175f3" UNIQUE ("slug"), CONSTRAINT "PK_098656ae401f3e1a4586f47fd8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_WORKSPACES_DELETED_AT" ON "workspaces" ("deleted_at") `);
        await queryRunner.query(`CREATE TYPE "public"."plans_billing_interval_enum" AS ENUM('MONTH', 'YEAR', 'LIFETIME')`);
        await queryRunner.query(`CREATE TABLE "plans" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "slug" character varying(100) NOT NULL, "description" text, "price_amount" integer NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "billing_interval" "public"."plans_billing_interval_enum" NOT NULL DEFAULT 'MONTH', "features" jsonb, "limits" jsonb, "is_active" boolean NOT NULL DEFAULT true, "sort_order" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_3720521a81c7c24fe9b7202ba61" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8ac30ab7d4ef974259069a8750" ON "plans" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_e7b71bb444e74ee067df057397" ON "plans" ("slug") `);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_provider_enum" AS ENUM('MANUAL', 'MOMO', 'VNPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."subscriptions_status_enum" AS ENUM('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', 'INCOMPLETE')`);
        await queryRunner.query(`CREATE TABLE "subscriptions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "provider" "public"."subscriptions_provider_enum" NOT NULL DEFAULT 'MANUAL', "provider_subscription_id" character varying(255), "status" "public"."subscriptions_status_enum" NOT NULL DEFAULT 'ACTIVE', "current_period_start" TIMESTAMP, "current_period_end" TIMESTAMP, "trial_end" TIMESTAMP, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "cancelled_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_a87248d73155605cf782be9ee5e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_4e80d5a85da612468d8158f506" ON "subscriptions" ("provider", "provider_subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1a15756e257e0eaf01edc85645" ON "subscriptions" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "IDX_6ccf973355b70645eff37774de" ON "subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_e45fca5d912c3a2fab512ac25d" ON "subscriptions" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d0a95ef8a28188364c546eb65c" ON "subscriptions" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."invoices_status_enum" AS ENUM('DRAFT', 'OPEN', 'PAID', 'VOID', 'UNCOLLECTIBLE')`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "subscription_id" uuid, "invoice_number" character varying(100) NOT NULL, "amount_due" integer NOT NULL DEFAULT '0', "amount_paid" integer NOT NULL DEFAULT '0', "currency" character varying(10) NOT NULL DEFAULT 'VND', "status" "public"."invoices_status_enum" NOT NULL DEFAULT 'OPEN', "period_start" TIMESTAMP, "period_end" TIMESTAMP, "hosted_invoice_url" text, "invoice_pdf_url" text, "due_at" TIMESTAMP, "paid_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ac0f09364e3701d9ed35435288" ON "invoices" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_d8f8d3788694e1b3f96c42c36f" ON "invoices" ("invoice_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_5152c0aa0f851d9b95972b442e" ON "invoices" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_08521b1e94fa456ac57f335485" ON "invoices" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_26daf5e433d6fb88ee32ce9363" ON "invoices" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."payments_provider_enum" AS ENUM('MANUAL', 'MOMO', 'VNPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_payment_method_enum" AS ENUM('QR', 'ATM', 'VISA', 'BANK_TRANSFER', 'WALLET', 'UNKNOWN')`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('PENDING', 'PROCESSING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'REFUNDED')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "target_workspace_id" uuid, "subscription_id" uuid, "invoice_id" uuid, "order_code" character varying(100) NOT NULL, "provider" "public"."payments_provider_enum" NOT NULL DEFAULT 'MANUAL', "provider_payment_id" character varying(255), "provider_order_id" character varying(255), "provider_request_id" character varying(255), "provider_transaction_id" character varying(255), "payment_method" "public"."payments_payment_method_enum" NOT NULL DEFAULT 'UNKNOWN', "amount" integer NOT NULL, "currency" character varying(10) NOT NULL DEFAULT 'VND', "status" "public"."payments_status_enum" NOT NULL DEFAULT 'PENDING', "payment_url" text, "expired_at" TIMESTAMP, "paid_at" TIMESTAMP, "failed_reason" text, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_712cfa59a1a682053302be2383" ON "payments" ("provider", "provider_transaction_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_27a9e16a54dda9e69d7555d5a5" ON "payments" ("provider", "provider_request_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_37eacc018c6ab6e3b033df34e9" ON "payments" ("provider", "provider_order_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_87606cc142b1a15c00445b647f" ON "payments" ("order_code") `);
        await queryRunner.query(`CREATE INDEX "IDX_32b41cdb985a296213e9a928b5" ON "payments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_30ab3d7a27e024409d8409601a" ON "payments" ("target_workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_563a5e248518c623eebd987d43" ON "payments" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_75848dfef07fd19027e08ca81d" ON "payments" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9b6a4c3196864cdd91b1a440e" ON "payments" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_427785468fb7d2733f59e7d7d3" ON "payments" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."billing_webhooks_provider_enum" AS ENUM('MANUAL', 'MOMO', 'VNPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."billing_webhooks_status_enum" AS ENUM('RECEIVED', 'PROCESSED', 'FAILED', 'IGNORED')`);
        await queryRunner.query(`CREATE TABLE "billing_webhooks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "target_workspace_id" uuid, "subscription_id" uuid, "payment_id" uuid, "invoice_id" uuid, "provider" "public"."billing_webhooks_provider_enum" NOT NULL, "provider_event_id" character varying(255) NOT NULL, "event_type" character varying(255) NOT NULL, "order_code" character varying(100), "provider_transaction_id" character varying(255), "status" "public"."billing_webhooks_status_enum" NOT NULL DEFAULT 'RECEIVED', "payload" jsonb NOT NULL, "processed_at" TIMESTAMP, "error_message" text, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_ed6e913d220f1564d85f68584b3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a809bf2073f818f5598870ca47" ON "billing_webhooks" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_a679b0c06c3447bce6b9b221a2" ON "billing_webhooks" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_ae20f0cef30a0636299478d3b9" ON "billing_webhooks" ("event_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_b4538478c6b35954cf27d206f6" ON "billing_webhooks" ("invoice_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_31d512028f7ffceaaedcbe42fa" ON "billing_webhooks" ("payment_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f086d4a8a01aaf7a8178860af1" ON "billing_webhooks" ("subscription_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_485f1bffef86b5fa73e7c8ade7" ON "billing_webhooks" ("target_workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_ace5ca855a1e27c42242781304" ON "billing_webhooks" ("user_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_2f7b512cb530d7ecbf1bc11140" ON "billing_webhooks" ("provider", "provider_event_id") `);
        await queryRunner.query(`CREATE TABLE "subscription_workspaces" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "subscription_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "activated_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0e797c417ac210a632baea85bf2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_75b5f60c57b4b668f9bb6f2fdd" ON "subscription_workspaces" ("subscription_id", "workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_9c6df002c443d02785a425c08c" ON "subscription_workspaces" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8986405225cf7db3310b27ff88" ON "subscription_workspaces" ("subscription_id") `);
        await queryRunner.query(`CREATE TYPE "public"."usage_limits_resource_type_enum" AS ENUM('MEMBERS', 'PROJECTS', 'TASKS', 'PAGES', 'PAGE_TEMPLATES', 'STORAGE_MB', 'ATTACHMENTS', 'SPRINTS')`);
        await queryRunner.query(`CREATE TABLE "usage_limits" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "plan_id" uuid, "resource_type" "public"."usage_limits_resource_type_enum" NOT NULL, "limit_value" integer, "used_value" integer NOT NULL DEFAULT '0', "reset_at" TIMESTAMP, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_fd1b4a9985764deab5c86fe23d2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_176541ede12e93282f7d3001f5" ON "usage_limits" ("plan_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_181e10fb568e8abc0f9fa80198" ON "usage_limits" ("workspace_id", "resource_type") `);
        await queryRunner.query(`CREATE TABLE "features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "name" character varying(150) NOT NULL, "description" text, "category" character varying(80), "is_active" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5c1e336df2f4a7051e5bf08a941" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1552375559043d106dc9014c55" ON "features" ("is_active") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_c0e1f5d0ba8027c186705d752b" ON "features" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."mentions_source_type_enum" AS ENUM('TASK_COMMENT', 'PAGE_COMMENT', 'PAGE_BLOCK')`);
        await queryRunner.query(`CREATE TYPE "public"."mentions_entity_type_enum" AS ENUM('TASK', 'PAGE', 'PAGE_BLOCK')`);
        await queryRunner.query(`CREATE TABLE "mentions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid, "mentioner_id" uuid NOT NULL, "mentioned_user_id" uuid NOT NULL, "source_type" "public"."mentions_source_type_enum" NOT NULL, "source_id" uuid NOT NULL, "entity_type" "public"."mentions_entity_type_enum" NOT NULL, "entity_id" uuid NOT NULL, "notification_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2c728c4685beaa7be19e11eae42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_08cc326bcc36b69774c6721e9a" ON "mentions" ("notification_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_d644737df1052524a913770615" ON "mentions" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_fa0f2f3576ba3faf0607be6445" ON "mentions" ("workspace_id", "source_type", "source_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_47d7917a734629d1cc15887086" ON "mentions" ("workspace_id", "mentioned_user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_sender_type_enum" AS ENUM('SYSTEM', 'USER')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_source_type_enum" AS ENUM('SYSTEM', 'ACCOUNT', 'WORKSPACE', 'PROJECT', 'TASK', 'SPRINT', 'COMMENT')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('SYSTEM_ANNOUNCEMENT', 'SYSTEM_MAINTENANCE', 'ACCOUNT_SECURITY', 'PASSWORD_CHANGED', 'EMAIL_VERIFIED', 'WORKSPACE_INVITE', 'WORKSPACE_INVITE_ACCEPTED', 'WORKSPACE_MEMBER_JOINED', 'WORKSPACE_MEMBER_REMOVED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'TASK_ASSIGNED', 'TASK_UPDATED', 'TASK_DUE_SOON', 'TASK_OVERDUE', 'SPRINT_STARTED', 'SPRINT_COMPLETED', 'COMMENT_MENTION', 'COMMENT_REPLY')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "receiver_id" uuid NOT NULL, "sender_type" "public"."notifications_sender_type_enum" NOT NULL DEFAULT 'SYSTEM', "actor_id" uuid, "source_type" "public"."notifications_source_type_enum" NOT NULL DEFAULT 'SYSTEM', "workspace_id" uuid, "project_id" uuid, "task_id" uuid, "sprint_id" uuid, "comment_id" uuid, "type" "public"."notifications_type_enum" NOT NULL, "title" character varying(255) NOT NULL, "message" text, "action_url" text, "metadata" jsonb, "read_at" TIMESTAMP, "archived_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_task_id" ON "notifications" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_project_id" ON "notifications" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_workspace_id" ON "notifications" ("workspace_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_receiver_read_at" ON "notifications" ("receiver_id", "read_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_notifications_receiver_created_at" ON "notifications" ("receiver_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."page_blocks_type_enum" AS ENUM('TEXT', 'HEADER', 'QUOTE', 'DIVIDER', 'CODE', 'TODO', 'IMAGE', 'VIDEO', 'FILE', 'BOOKMARK', 'EMBED', 'FIGMA', 'GITHUB_GIST', 'GOOGLE_MAPS', 'TWEET', 'DATABASE_VIEW', 'TABLE_SIMPLE', 'MERMAID', 'BUTTON')`);
        await queryRunner.query(`CREATE TABLE "page_blocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "page_id" uuid NOT NULL, "type" "public"."page_blocks_type_enum" NOT NULL, "title" character varying, "order_index" integer NOT NULL DEFAULT '0', "position_x" integer, "position_y" integer, "width" integer, "height" integer, "content" jsonb, "data_config" jsonb, "style_config" jsonb, "created_by" uuid NOT NULL, "is_open" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "PK_da57feac0f4c851a6419487176b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PAGE_BLOCKS_PAGE_ORDER_ACTIVE" ON "page_blocks" ("page_id", "order_index") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_PAGE_BLOCKS_DELETED_AT" ON "page_blocks" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAGE_BLOCKS_PAGE_ID" ON "page_blocks" ("page_id") `);
        await queryRunner.query(`CREATE TABLE "pages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "title" character varying(255) NOT NULL, "slug" character varying(255), "icon" character varying(255), "cover_url" text, "is_template" boolean NOT NULL DEFAULT false, "created_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "deleted_by" uuid, CONSTRAINT "PK_8f21ed625aa34c8391d636b7d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_PAGES_WORKSPACE_SLUG_ACTIVE" ON "pages" ("workspace_id", "slug") WHERE "deleted_at" IS NULL`);
        await queryRunner.query(`CREATE INDEX "IDX_PAGES_DELETED_AT" ON "pages" ("deleted_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_PAGES_WORKSPACE_ID" ON "pages" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "page_template_blocks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "template_id" uuid NOT NULL, "parent_block_id" uuid, "type" character varying(100) NOT NULL, "content" jsonb, "order_index" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_6c101f8b441c5979cb276c4878c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_447c6640293687c7b23aa847e1" ON "page_template_blocks" ("parent_block_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_1589dbc502d1c94df485cd6a58" ON "page_template_blocks" ("template_id", "order_index") `);
        await queryRunner.query(`CREATE INDEX "IDX_7bcdeb9feaeaf76b2b12dcd63d" ON "page_template_blocks" ("template_id") `);
        await queryRunner.query(`CREATE TYPE "public"."page_templates_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."page_templates_visibility_enum" AS ENUM('PRIVATE', 'WORKSPACE', 'PUBLIC', 'PUBLIC_PENDING')`);
        await queryRunner.query(`CREATE TABLE "page_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid, "name" character varying(255) NOT NULL, "description" text, "icon" character varying(100), "cover_url" text, "category" character varying(100), "is_system" boolean NOT NULL DEFAULT false, "created_by" uuid, "status" "public"."page_templates_status_enum" NOT NULL DEFAULT 'DRAFT', "visibility" "public"."page_templates_visibility_enum" NOT NULL DEFAULT 'PRIVATE', "use_count" integer NOT NULL DEFAULT '0', "likes_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_f6263e9e28902172839e84b554b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1db58ca29e8f9cfb09276e14db" ON "page_templates" ("status", "visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_58bb1789bf717565065285da1a" ON "page_templates" ("is_system") `);
        await queryRunner.query(`CREATE INDEX "IDX_de38328ab305acccaca02ba3bd" ON "page_templates" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_183935f53af20e942d693e2b44" ON "page_templates" ("workspace_id", "name") `);
        await queryRunner.query(`CREATE INDEX "IDX_c7ae07a4b119fa5660e081fb07" ON "page_templates" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "code" character varying(100) NOT NULL, "description" character varying(255), "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_8dad765629e83229da6feda1c1d" UNIQUE ("code"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "plan_features" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "plan_id" uuid NOT NULL, "feature_id" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT true, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_eb2b32d1d93a8b2e96e122e3a77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_036c6f8f3800d80eca204293de" ON "plan_features" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_27e866bdf4c6f2cf5854b7d0e5" ON "plan_features" ("feature_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b51952483b18fa15334d714a83" ON "plan_features" ("plan_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_03b01312e81d9165f8a2636b58" ON "plan_features" ("plan_id", "feature_id") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token" character varying(512) NOT NULL, "user_agent" character varying(255), "ip_address" inet, "expires_at" TIMESTAMP NOT NULL, "revoked_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_refresh_token_user" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_refresh_token_token" ON "refresh_tokens" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."roles_name_enum" AS ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" "public"."roles_name_enum" NOT NULL, "workspace_id" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_role_workspace_name" ON "roles" ("workspace_id", "name") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_permission" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_role_permissions_role" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "sprint_reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "sprint_id" uuid NOT NULL, "sprint_name" character varying(255) NOT NULL, "sprint_goal" character varying(500), "total_tasks" integer NOT NULL DEFAULT '0', "completed_tasks" integer NOT NULL DEFAULT '0', "incomplete_tasks" integer NOT NULL DEFAULT '0', "total_estimate" integer NOT NULL DEFAULT '0', "completed_estimate" integer NOT NULL DEFAULT '0', "completed_task_ids" jsonb NOT NULL DEFAULT '[]', "incomplete_task_ids" jsonb NOT NULL DEFAULT '[]', "member_performance" jsonb NOT NULL DEFAULT '[]', "completed_task_details" jsonb NOT NULL DEFAULT '[]', "incomplete_task_details" jsonb NOT NULL DEFAULT '[]', "start_at" TIMESTAMP, "completed_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_48a4ff998c0d4fdea1e98455327" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_SPRINT_REPORTS_SPRINT_ID" ON "sprint_reports" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_f2f46a5de0e574de2142dd321f" ON "sprint_reports" ("sprint_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_90b28d1da4a183ac50b0bd3c67" ON "sprint_reports" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_cef552ef14cbb2a3ed1d7ba584" ON "sprint_reports" ("workspace_id") `);
        await queryRunner.query(`CREATE TABLE "task_comments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "project_id" uuid NOT NULL, "task_id" uuid NOT NULL, "author_id" uuid NOT NULL, "content" text NOT NULL, "is_edited" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_83b99b0b03db29d4cafcb579b77" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_COMMENTS_TASK_CREATED_AT" ON "task_comments" ("task_id", "created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_COMMENTS_AUTHOR_ID" ON "task_comments" ("author_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_COMMENTS_TASK_ID" ON "task_comments" ("task_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_COMMENTS_PROJECT_ID" ON "task_comments" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_TASK_COMMENTS_WORKSPACE_ID" ON "task_comments" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."user_activity_type_enum" AS ENUM('LOGIN', 'OPEN_APP', 'OPEN_WORKSPACE', 'REFRESH_TOKEN')`);
        await queryRunner.query(`CREATE TABLE "user_activities" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "type" "public"."user_activity_type_enum" NOT NULL DEFAULT 'OPEN_APP', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1245d4d2cf04ba7743f2924d951" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_user_activities_created_at" ON "user_activities" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_user_activities_user_id" ON "user_activities" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "role_id" uuid NOT NULL, "assigned_at" TIMESTAMP NOT NULL DEFAULT now(), "assigned_by" uuid, CONSTRAINT "PK_3868a216bfe72626b8b80e1dc4f" PRIMARY KEY ("user_id", "workspace_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_user_roles_workspace_user" ON "user_roles" ("workspace_id", "user_id") `);
        await queryRunner.query(`CREATE TABLE "workspace_feature_settings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "feature_id" uuid NOT NULL, "enabled" boolean NOT NULL DEFAULT false, "created_by" uuid, "updated_by" uuid, "metadata" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_5d594450a26530ec47127a0d111" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_8f3d24439be7ec018023fbafef" ON "workspace_feature_settings" ("enabled") `);
        await queryRunner.query(`CREATE INDEX "IDX_d05d2a5f46cd5768f2e63fd482" ON "workspace_feature_settings" ("feature_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e7d3027d64c7c874528d5080e2" ON "workspace_feature_settings" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_fe583d649a496665715c2a0c24" ON "workspace_feature_settings" ("workspace_id", "feature_id") `);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_type_enum" AS ENUM('EMAIL', 'LINK')`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_role_name_enum" AS ENUM('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_status_enum" AS ENUM('PENDING', 'ACCEPTED', 'EXPIRED', 'REVOKED')`);
        await queryRunner.query(`CREATE TABLE "workspace_invites" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "workspace_id" uuid NOT NULL, "user_id" uuid, "email" character varying(255), "type" "public"."workspace_invites_type_enum" NOT NULL DEFAULT 'EMAIL', "role_name" "public"."workspace_invites_role_name_enum" NOT NULL DEFAULT 'MEMBER', "invited_by" uuid NOT NULL, "token" character varying(255) NOT NULL, "status" "public"."workspace_invites_status_enum" NOT NULL DEFAULT 'PENDING', "accepted_at" TIMESTAMP, "expires_at" TIMESTAMP NOT NULL, "max_uses" integer, "used_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_43f7a0e0b0549fe2581e9cb57bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_type" ON "workspace_invites" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_user_id" ON "workspace_invites" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_invited_by" ON "workspace_invites" ("invited_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_status" ON "workspace_invites" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_email" ON "workspace_invites" ("email") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_invites_workspace_id" ON "workspace_invites" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_workspace_invites_token" ON "workspace_invites" ("token") `);
        await queryRunner.query(`CREATE TYPE "public"."workspace_templates_status_enum" AS ENUM('DRAFT', 'PUBLISHED', 'ARCHIVED')`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_templates_visibility_enum" AS ENUM('PRIVATE', 'WORKSPACE', 'PUBLIC', 'PUBLIC_PENDING')`);
        await queryRunner.query(`CREATE TABLE "workspace_templates" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL, "description" text, "category" character varying(100), "cover_url" text, "config" jsonb NOT NULL, "is_system" boolean NOT NULL DEFAULT true, "page_template_id" uuid, "status" "public"."workspace_templates_status_enum" NOT NULL DEFAULT 'DRAFT', "visibility" "public"."workspace_templates_visibility_enum" NOT NULL DEFAULT 'PRIVATE', "created_by" uuid, "workspace_id" uuid, "use_count" integer NOT NULL DEFAULT '0', "likes_count" integer NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, CONSTRAINT "PK_51e21f5cf8dcaf4bf016878f998" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1d4a5e3435cc5d5d62ce12aaba" ON "workspace_templates" ("status", "visibility") `);
        await queryRunner.query(`CREATE INDEX "IDX_9ce729d826830a0df18a04ac98" ON "workspace_templates" ("is_system") `);
        await queryRunner.query(`CREATE INDEX "IDX_c5d1197b4d500cba051a5f4722" ON "workspace_templates" ("created_by") `);
        await queryRunner.query(`CREATE INDEX "IDX_d7609d8e69a95ff97432ebe349" ON "workspace_templates" ("workspace_id") `);
        await queryRunner.query(`ALTER TABLE "user_profiles" ADD CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_bf217cf96eaeb253a7cd35b52ad" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_1542ae826c0dfeaf4c79e07fc57" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_8156e1b3bd94cb1812a6d55375c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "boards" ADD CONSTRAINT "FK_983b7eec43b4188489af2981a0e" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_0141288f2306f20da9a60ec8d69" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_bb8051e376a2b083e074678cb60" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_assignees" ADD CONSTRAINT "FK_44aef1f0e96ef4afc8d9b1f14df" FOREIGN KEY ("assigned_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_priorities" ADD CONSTRAINT "FK_9f5351226f12f052b9da79af93f" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_priorities" ADD CONSTRAINT "FK_90cb292b1088ae8027d5843edef" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_statuses" ADD CONSTRAINT "FK_5306f541f83255c6c0ca251189f" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_statuses" ADD CONSTRAINT "FK_1918c92dc3fb9fd3b0df2e6a7e4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_5cb6ca4667dfa947871694da959" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_b512d5a489d692f66569978b8a7" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_e28288969fa7827bd12680cfe10" FOREIGN KEY ("status_id") REFERENCES "task_statuses"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_5d1c8f7898b5b84ad5ce08fcff8" FOREIGN KEY ("priority_id") REFERENCES "task_priorities"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasks" ADD CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4" FOREIGN KEY ("reporter_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_8377d578af0d41c855635574ddd" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_82145010051f3f2fc94671c0b35" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprints" ADD CONSTRAINT "FK_7f57ff76f3ed56db4147ff03498" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" ADD CONSTRAINT "FK_b2c27397c6389ce190d492d30da" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" ADD CONSTRAINT "FK_87fe6693df535a622eaf4248697" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscriptions" ADD CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_08521b1e94fa456ac57f335485f" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "invoices" ADD CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_427785468fb7d2733f59e7d7d39" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_f9b6a4c3196864cdd91b1a440ee" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_30ab3d7a27e024409d8409601af" FOREIGN KEY ("target_workspace_id") REFERENCES "workspaces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_75848dfef07fd19027e08ca81d2" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_563a5e248518c623eebd987d43e" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" ADD CONSTRAINT "FK_ace5ca855a1e27c42242781304e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" ADD CONSTRAINT "FK_485f1bffef86b5fa73e7c8ade7f" FOREIGN KEY ("target_workspace_id") REFERENCES "workspaces"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" ADD CONSTRAINT "FK_f086d4a8a01aaf7a8178860af1d" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" ADD CONSTRAINT "FK_31d512028f7ffceaaedcbe42fa4" FOREIGN KEY ("payment_id") REFERENCES "payments"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" ADD CONSTRAINT "FK_b4538478c6b35954cf27d206f63" FOREIGN KEY ("invoice_id") REFERENCES "invoices"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_workspaces" ADD CONSTRAINT "FK_8986405225cf7db3310b27ff885" FOREIGN KEY ("subscription_id") REFERENCES "subscriptions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "subscription_workspaces" ADD CONSTRAINT "FK_9c6df002c443d02785a425c08c9" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_limits" ADD CONSTRAINT "FK_5181cfb598d266c5a979fcf1150" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "usage_limits" ADD CONSTRAINT "FK_176541ede12e93282f7d3001f56" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_343c8ee2cd2f4036f2a3423989e" FOREIGN KEY ("receiver_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6" FOREIGN KEY ("actor_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_blocks" ADD CONSTRAINT "FK_ad019765c7ffab9084d1d215d48" FOREIGN KEY ("page_id") REFERENCES "pages"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "page_blocks" ADD CONSTRAINT "FK_c04e1bba3158ed15a30eee0349c" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_e81517e2f307170573c9be6f581" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "pages" ADD CONSTRAINT "FK_064ab67bb29a28d073db287fc6d" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_features" ADD CONSTRAINT "FK_b51952483b18fa15334d714a838" FOREIGN KEY ("plan_id") REFERENCES "plans"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "plan_features" ADD CONSTRAINT "FK_27e866bdf4c6f2cf5854b7d0e57" FOREIGN KEY ("feature_id") REFERENCES "features"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ADD CONSTRAINT "FK_5291e7ee78e540217bd44bd3688" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_reports" ADD CONSTRAINT "FK_cef552ef14cbb2a3ed1d7ba5849" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_reports" ADD CONSTRAINT "FK_90b28d1da4a183ac50b0bd3c67f" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sprint_reports" ADD CONSTRAINT "FK_f2f46a5de0e574de2142dd321f0" FOREIGN KEY ("sprint_id") REFERENCES "sprints"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_ba9e465cfc707006e60aae59946" FOREIGN KEY ("task_id") REFERENCES "tasks"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "task_comments" ADD CONSTRAINT "FK_76901a920ba9ec5be8dbd64d747" FOREIGN KEY ("author_id") REFERENCES "users"("id") ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_activities" ADD CONSTRAINT "FK_a283f37e08edf5e37d38b375eec" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_4cd2a0a1566d9ddcab3068ac642" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" ADD CONSTRAINT "FK_e7d3027d64c7c874528d5080e28" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" ADD CONSTRAINT "FK_d05d2a5f46cd5768f2e63fd4821" FOREIGN KEY ("feature_id") REFERENCES "features"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" ADD CONSTRAINT "FK_87e1229bdfe77897adb4dafa583" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" ADD CONSTRAINT "FK_96ad4d782f2db292c0c5bd364b3" FOREIGN KEY ("updated_by") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ADD CONSTRAINT "FK_9ffc4e5b893e8fb91d66d466f6d" FOREIGN KEY ("workspace_id") REFERENCES "workspaces"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ADD CONSTRAINT "FK_93d8174e8b1537da7b092621c7f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ADD CONSTRAINT "FK_cf390e54ae1d8871cb74aad9c89" FOREIGN KEY ("invited_by") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "workspace_invites" DROP CONSTRAINT "FK_cf390e54ae1d8871cb74aad9c89"`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" DROP CONSTRAINT "FK_93d8174e8b1537da7b092621c7f"`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" DROP CONSTRAINT "FK_9ffc4e5b893e8fb91d66d466f6d"`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" DROP CONSTRAINT "FK_96ad4d782f2db292c0c5bd364b3"`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" DROP CONSTRAINT "FK_87e1229bdfe77897adb4dafa583"`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" DROP CONSTRAINT "FK_d05d2a5f46cd5768f2e63fd4821"`);
        await queryRunner.query(`ALTER TABLE "workspace_feature_settings" DROP CONSTRAINT "FK_e7d3027d64c7c874528d5080e28"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_4cd2a0a1566d9ddcab3068ac642"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "user_activities" DROP CONSTRAINT "FK_a283f37e08edf5e37d38b375eec"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_76901a920ba9ec5be8dbd64d747"`);
        await queryRunner.query(`ALTER TABLE "task_comments" DROP CONSTRAINT "FK_ba9e465cfc707006e60aae59946"`);
        await queryRunner.query(`ALTER TABLE "sprint_reports" DROP CONSTRAINT "FK_f2f46a5de0e574de2142dd321f0"`);
        await queryRunner.query(`ALTER TABLE "sprint_reports" DROP CONSTRAINT "FK_90b28d1da4a183ac50b0bd3c67f"`);
        await queryRunner.query(`ALTER TABLE "sprint_reports" DROP CONSTRAINT "FK_cef552ef14cbb2a3ed1d7ba5849"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "roles" DROP CONSTRAINT "FK_5291e7ee78e540217bd44bd3688"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_3ddc983c5f7bcf132fd8732c3f4"`);
        await queryRunner.query(`ALTER TABLE "plan_features" DROP CONSTRAINT "FK_27e866bdf4c6f2cf5854b7d0e57"`);
        await queryRunner.query(`ALTER TABLE "plan_features" DROP CONSTRAINT "FK_b51952483b18fa15334d714a838"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_064ab67bb29a28d073db287fc6d"`);
        await queryRunner.query(`ALTER TABLE "pages" DROP CONSTRAINT "FK_e81517e2f307170573c9be6f581"`);
        await queryRunner.query(`ALTER TABLE "page_blocks" DROP CONSTRAINT "FK_c04e1bba3158ed15a30eee0349c"`);
        await queryRunner.query(`ALTER TABLE "page_blocks" DROP CONSTRAINT "FK_ad019765c7ffab9084d1d215d48"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_20f8b51fd9655c0b69feed5efc6"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_343c8ee2cd2f4036f2a3423989e"`);
        await queryRunner.query(`ALTER TABLE "usage_limits" DROP CONSTRAINT "FK_176541ede12e93282f7d3001f56"`);
        await queryRunner.query(`ALTER TABLE "usage_limits" DROP CONSTRAINT "FK_5181cfb598d266c5a979fcf1150"`);
        await queryRunner.query(`ALTER TABLE "subscription_workspaces" DROP CONSTRAINT "FK_9c6df002c443d02785a425c08c9"`);
        await queryRunner.query(`ALTER TABLE "subscription_workspaces" DROP CONSTRAINT "FK_8986405225cf7db3310b27ff885"`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" DROP CONSTRAINT "FK_b4538478c6b35954cf27d206f63"`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" DROP CONSTRAINT "FK_31d512028f7ffceaaedcbe42fa4"`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" DROP CONSTRAINT "FK_f086d4a8a01aaf7a8178860af1d"`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" DROP CONSTRAINT "FK_485f1bffef86b5fa73e7c8ade7f"`);
        await queryRunner.query(`ALTER TABLE "billing_webhooks" DROP CONSTRAINT "FK_ace5ca855a1e27c42242781304e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_563a5e248518c623eebd987d43e"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_75848dfef07fd19027e08ca81d2"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_30ab3d7a27e024409d8409601af"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_f9b6a4c3196864cdd91b1a440ee"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_427785468fb7d2733f59e7d7d39"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_5152c0aa0f851d9b95972b442e0"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_08521b1e94fa456ac57f335485f"`);
        await queryRunner.query(`ALTER TABLE "invoices" DROP CONSTRAINT "FK_26daf5e433d6fb88ee32ce93637"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_e45fca5d912c3a2fab512ac25dc"`);
        await queryRunner.query(`ALTER TABLE "subscriptions" DROP CONSTRAINT "FK_d0a95ef8a28188364c546eb65c1"`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" DROP CONSTRAINT "FK_87fe6693df535a622eaf4248697"`);
        await queryRunner.query(`ALTER TABLE "user_workspaces" DROP CONSTRAINT "FK_b2c27397c6389ce190d492d30da"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_af78b8fc6857fe0a10d1bb1699e"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_7f57ff76f3ed56db4147ff03498"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_82145010051f3f2fc94671c0b35"`);
        await queryRunner.query(`ALTER TABLE "sprints" DROP CONSTRAINT "FK_8377d578af0d41c855635574ddd"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_87d662c4ff7beec6ad017466fc4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_5d1c8f7898b5b84ad5ce08fcff8"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_e28288969fa7827bd12680cfe10"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_b512d5a489d692f66569978b8a7"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_9eecdb5b1ed8c7c2a1b392c28d4"`);
        await queryRunner.query(`ALTER TABLE "tasks" DROP CONSTRAINT "FK_5cb6ca4667dfa947871694da959"`);
        await queryRunner.query(`ALTER TABLE "task_statuses" DROP CONSTRAINT "FK_1918c92dc3fb9fd3b0df2e6a7e4"`);
        await queryRunner.query(`ALTER TABLE "task_statuses" DROP CONSTRAINT "FK_5306f541f83255c6c0ca251189f"`);
        await queryRunner.query(`ALTER TABLE "task_priorities" DROP CONSTRAINT "FK_90cb292b1088ae8027d5843edef"`);
        await queryRunner.query(`ALTER TABLE "task_priorities" DROP CONSTRAINT "FK_9f5351226f12f052b9da79af93f"`);
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_44aef1f0e96ef4afc8d9b1f14df"`);
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_bb8051e376a2b083e074678cb60"`);
        await queryRunner.query(`ALTER TABLE "task_assignees" DROP CONSTRAINT "FK_0141288f2306f20da9a60ec8d69"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_983b7eec43b4188489af2981a0e"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_8156e1b3bd94cb1812a6d55375c"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_1542ae826c0dfeaf4c79e07fc57"`);
        await queryRunner.query(`ALTER TABLE "boards" DROP CONSTRAINT "FK_bf217cf96eaeb253a7cd35b52ad"`);
        await queryRunner.query(`ALTER TABLE "user_profiles" DROP CONSTRAINT "FK_6ca9503d77ae39b4b5a6cc3ba88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d7609d8e69a95ff97432ebe349"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5d1197b4d500cba051a5f4722"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9ce729d826830a0df18a04ac98"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1d4a5e3435cc5d5d62ce12aaba"`);
        await queryRunner.query(`DROP TABLE "workspace_templates"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_templates_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_templates_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_workspace_invites_token"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_email"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_status"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_invited_by"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_invites_type"`);
        await queryRunner.query(`DROP TABLE "workspace_invites"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_role_name_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe583d649a496665715c2a0c24"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7d3027d64c7c874528d5080e2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d05d2a5f46cd5768f2e63fd482"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f3d24439be7ec018023fbafef"`);
        await queryRunner.query(`DROP TABLE "workspace_feature_settings"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_roles_workspace_user"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_activities_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_activities_created_at"`);
        await queryRunner.query(`DROP TABLE "user_activities"`);
        await queryRunner.query(`DROP TYPE "public"."user_activity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_COMMENTS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_COMMENTS_PROJECT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_COMMENTS_TASK_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_COMMENTS_AUTHOR_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_COMMENTS_TASK_CREATED_AT"`);
        await queryRunner.query(`DROP TABLE "task_comments"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cef552ef14cbb2a3ed1d7ba584"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_90b28d1da4a183ac50b0bd3c67"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f2f46a5de0e574de2142dd321f"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_SPRINT_REPORTS_SPRINT_ID"`);
        await queryRunner.query(`DROP TABLE "sprint_reports"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_role"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_role_permissions_permission"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_role_workspace_name"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TYPE "public"."roles_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_token_token"`);
        await queryRunner.query(`DROP INDEX "public"."idx_refresh_token_user"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_03b01312e81d9165f8a2636b58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b51952483b18fa15334d714a83"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27e866bdf4c6f2cf5854b7d0e5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_036c6f8f3800d80eca204293de"`);
        await queryRunner.query(`DROP TABLE "plan_features"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c7ae07a4b119fa5660e081fb07"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_183935f53af20e942d693e2b44"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_de38328ab305acccaca02ba3bd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_58bb1789bf717565065285da1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1db58ca29e8f9cfb09276e14db"`);
        await queryRunner.query(`DROP TABLE "page_templates"`);
        await queryRunner.query(`DROP TYPE "public"."page_templates_visibility_enum"`);
        await queryRunner.query(`DROP TYPE "public"."page_templates_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7bcdeb9feaeaf76b2b12dcd63d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1589dbc502d1c94df485cd6a58"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_447c6640293687c7b23aa847e1"`);
        await queryRunner.query(`DROP TABLE "page_template_blocks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAGES_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAGES_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PAGES_WORKSPACE_SLUG_ACTIVE"`);
        await queryRunner.query(`DROP TABLE "pages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAGE_BLOCKS_PAGE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PAGE_BLOCKS_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PAGE_BLOCKS_PAGE_ORDER_ACTIVE"`);
        await queryRunner.query(`DROP TABLE "page_blocks"`);
        await queryRunner.query(`DROP TYPE "public"."page_blocks_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_receiver_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_receiver_read_at"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_project_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_notifications_task_id"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_source_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_sender_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_47d7917a734629d1cc15887086"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fa0f2f3576ba3faf0607be6445"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d644737df1052524a913770615"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08cc326bcc36b69774c6721e9a"`);
        await queryRunner.query(`DROP TABLE "mentions"`);
        await queryRunner.query(`DROP TYPE "public"."mentions_entity_type_enum"`);
        await queryRunner.query(`DROP TYPE "public"."mentions_source_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0e1f5d0ba8027c186705d752b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1552375559043d106dc9014c55"`);
        await queryRunner.query(`DROP TABLE "features"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_181e10fb568e8abc0f9fa80198"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_176541ede12e93282f7d3001f5"`);
        await queryRunner.query(`DROP TABLE "usage_limits"`);
        await queryRunner.query(`DROP TYPE "public"."usage_limits_resource_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8986405225cf7db3310b27ff88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_9c6df002c443d02785a425c08c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75b5f60c57b4b668f9bb6f2fdd"`);
        await queryRunner.query(`DROP TABLE "subscription_workspaces"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2f7b512cb530d7ecbf1bc11140"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ace5ca855a1e27c42242781304"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_485f1bffef86b5fa73e7c8ade7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f086d4a8a01aaf7a8178860af1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31d512028f7ffceaaedcbe42fa"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b4538478c6b35954cf27d206f6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ae20f0cef30a0636299478d3b9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a679b0c06c3447bce6b9b221a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a809bf2073f818f5598870ca47"`);
        await queryRunner.query(`DROP TABLE "billing_webhooks"`);
        await queryRunner.query(`DROP TYPE "public"."billing_webhooks_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."billing_webhooks_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_427785468fb7d2733f59e7d7d3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9b6a4c3196864cdd91b1a440e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75848dfef07fd19027e08ca81d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_563a5e248518c623eebd987d43"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_30ab3d7a27e024409d8409601a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_32b41cdb985a296213e9a928b5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87606cc142b1a15c00445b647f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_37eacc018c6ab6e3b033df34e9"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_27a9e16a54dda9e69d7555d5a5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_712cfa59a1a682053302be2383"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_payment_method_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payments_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_26daf5e433d6fb88ee32ce9363"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_08521b1e94fa456ac57f335485"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5152c0aa0f851d9b95972b442e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d8f8d3788694e1b3f96c42c36f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ac0f09364e3701d9ed35435288"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TYPE "public"."invoices_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d0a95ef8a28188364c546eb65c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e45fca5d912c3a2fab512ac25d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6ccf973355b70645eff37774de"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1a15756e257e0eaf01edc85645"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e80d5a85da612468d8158f506"`);
        await queryRunner.query(`DROP TABLE "subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."subscriptions_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e7b71bb444e74ee067df057397"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8ac30ab7d4ef974259069a8750"`);
        await queryRunner.query(`DROP TABLE "plans"`);
        await queryRunner.query(`DROP TYPE "public"."plans_billing_interval_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_WORKSPACES_DELETED_AT"`);
        await queryRunner.query(`DROP TABLE "workspaces"`);
        await queryRunner.query(`DROP TYPE "public"."workspaces_layout_mode_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspaces_plan_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_user_workspaces_workspace_user"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_workspaces_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_user_workspaces_workspace_id"`);
        await queryRunner.query(`DROP TABLE "user_workspaces"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_PROJECTS_WORKSPACE_KEY_ACTIVE"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROJECTS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_PROJECTS_DELETED_AT"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TYPE "public"."projects_visibility_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8377d578af0d41c855635574dd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_82145010051f3f2fc94671c0b3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_507d36b62bcb05326a1afb3e88"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_SPRINTS_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_SPRINTS_PROJECT_NAME_ACTIVE"`);
        await queryRunner.query(`DROP TABLE "sprints"`);
        await queryRunner.query(`DROP TYPE "public"."sprints_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_TASKS_PROJECT_SEQ"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_PROJECT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_STATUS_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_PRIORITY_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_CREATED_BY"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_SPRINT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASKS_DELETED_AT"`);
        await queryRunner.query(`DROP TABLE "tasks"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abd81daad5031170fd80eb270d"`);
        await queryRunner.query(`DROP TABLE "task_statuses"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0b8db587f3fa0723369398ac37"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8a5da24ee33550e6a8b36d960a"`);
        await queryRunner.query(`DROP TABLE "task_priorities"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_TASK_ASSIGNEES_TASK_USER"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_ASSIGNEES_TASK_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_ASSIGNEES_USER_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_TASK_ASSIGNEES_ASSIGNED_BY"`);
        await queryRunner.query(`DROP TABLE "task_assignees"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOARDS_WORKSPACE_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOARDS_PROJECT_ID"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_BOARDS_DELETED_AT"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_BOARDS_PROJECT_NAME_ACTIVE"`);
        await queryRunner.query(`DROP TABLE "boards"`);
        await queryRunner.query(`DROP TYPE "public"."boards_view_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0bd5012aeb82628e07f6a1be53"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_fe0bb3f6520ee0469504521e71"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_system_role_enum"`);
        await queryRunner.query(`DROP TABLE "user_profiles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e140f8ddef870ea93925f251f2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177183f29f438c488b5e8510cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_959054ba1c3ad6190ce3f7c754"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_entity_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_244c5f17089416157f6dc9190f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7eb55326eb220fef58d00cccbf"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ec3648b85f6af7eafe865a3257"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3fb5314ef323d02aed62ccb283"`);
        await queryRunner.query(`DROP TABLE "attachments"`);
        await queryRunner.query(`DROP TYPE "public"."attachments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."attachments_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_70f034bc5912fde02b82b329f1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bca646bf128e29d7b1f5fd2339"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_789eee36df14bb2a655b087404"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_78e06b2e7a3bd9b9239de4aa28"`);
        await queryRunner.query(`DROP TABLE "activities"`);
        await queryRunner.query(`DROP TYPE "public"."activities_action_enum"`);
        await queryRunner.query(`DROP TYPE "public"."activities_entity_type_enum"`);
    }

}
