import { MigrationInterface, QueryRunner } from "typeorm";

export class InitSchema1788514253326 implements MigrationInterface {
    name = 'InitSchema1788514253326'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."billing_features_value_type_enum" AS ENUM('BOOLEAN', 'NUMBER', 'STRING')`);
        await queryRunner.query(`CREATE TABLE "billing_features" ("id" uuid NOT NULL, "code" character varying(150) NOT NULL, "name" character varying(150) NOT NULL, "description" text, "value_type" "public"."billing_features_value_type_enum" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a8bc438832e49a9bb339cbdf6c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_billing_features_code" ON "billing_features" ("code") `);
        await queryRunner.query(`CREATE TABLE "billing_plan_features" ("id" uuid NOT NULL, "plan_id" uuid NOT NULL, "feature_id" uuid NOT NULL, "value" jsonb NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_billing_plan_features_plan_feature" UNIQUE ("plan_id", "feature_id"), CONSTRAINT "PK_95915b33ed4097d8fa68634e5cd" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_billing_plan_features_feature_id" ON "billing_plan_features" ("feature_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_billing_plan_features_plan_id" ON "billing_plan_features" ("plan_id") `);
        await queryRunner.query(`CREATE TYPE "public"."billing_plan_prices_billing_interval_enum" AS ENUM('MONTHLY', 'YEARLY')`);
        await queryRunner.query(`CREATE TYPE "public"."billing_plan_prices_provider_enum" AS ENUM('STRIPE', 'SEPAY')`);
        await queryRunner.query(`CREATE TABLE "billing_plan_prices" ("id" uuid NOT NULL, "plan_id" uuid NOT NULL, "billing_interval" "public"."billing_plan_prices_billing_interval_enum" NOT NULL, "currency" character varying(3) NOT NULL, "amount" bigint NOT NULL, "provider" "public"."billing_plan_prices_provider_enum" NOT NULL, "provider_price_id" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_cf502d85d2cf0499c929d86a43e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_billing_plan_prices_provider" ON "billing_plan_prices" ("provider") `);
        await queryRunner.query(`CREATE INDEX "IDX_billing_plan_prices_plan_id" ON "billing_plan_prices" ("plan_id") `);
        await queryRunner.query(`CREATE TABLE "billing_plans" ("id" uuid NOT NULL, "code" character varying(100) NOT NULL, "name" character varying(150) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "is_public" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_f5dd8c47fbdcd68a43b97f9795e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_billing_plans_code" ON "billing_plans" ("code") `);
        await queryRunner.query(`CREATE TABLE "billing_usage" ("id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "feature_id" uuid NOT NULL, "period_start" TIMESTAMP WITH TIME ZONE NOT NULL, "period_end" TIMESTAMP WITH TIME ZONE NOT NULL, "used_value" bigint NOT NULL DEFAULT '0', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_billing_usage_workspace_feature_period" UNIQUE ("workspace_id", "feature_id", "period_start", "period_end"), CONSTRAINT "PK_55b77cbbebecd847e5c71420846" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_billing_usage_feature_id" ON "billing_usage" ("feature_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_billing_usage_workspace_id" ON "billing_usage" ("workspace_id") `);
        await queryRunner.query(`CREATE TYPE "public"."billing_webhook_events_provider_enum" AS ENUM('STRIPE', 'SEPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."billing_webhook_events_status_enum" AS ENUM('PENDING', 'PROCESSED', 'FAILED', 'IGNORED')`);
        await queryRunner.query(`CREATE TABLE "billing_webhook_events" ("id" uuid NOT NULL, "provider" "public"."billing_webhook_events_provider_enum" NOT NULL, "provider_event_id" character varying(255) NOT NULL, "event_type" character varying(255) NOT NULL, "payload" jsonb NOT NULL, "status" "public"."billing_webhook_events_status_enum" NOT NULL DEFAULT 'PENDING', "processed_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_billing_webhook_events_provider_event" UNIQUE ("provider", "provider_event_id"), CONSTRAINT "PK_a4c2d2eae68da905a0b6063d0ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_billing_webhook_events_status" ON "billing_webhook_events" ("status") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_orders_provider_enum" AS ENUM('STRIPE', 'SEPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_orders_status_enum" AS ENUM('PENDING', 'PAID', 'FAILED', 'EXPIRED', 'CANCELED')`);
        await queryRunner.query(`CREATE TABLE "payment_orders" ("id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "subscription_id" uuid, "plan_price_id" uuid NOT NULL, "provider" "public"."payment_orders_provider_enum" NOT NULL, "order_code" character varying(100) NOT NULL, "amount" bigint NOT NULL, "currency" character varying(3) NOT NULL, "status" "public"."payment_orders_status_enum" NOT NULL DEFAULT 'PENDING', "expires_at" TIMESTAMP WITH TIME ZONE, "paid_at" TIMESTAMP WITH TIME ZONE, "created_by" uuid NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_158dd178010c39759305293a149" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payment_orders_status" ON "payment_orders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_payment_orders_workspace_id" ON "payment_orders" ("workspace_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "UQ_payment_orders_order_code" ON "payment_orders" ("order_code") `);
        await queryRunner.query(`CREATE TYPE "public"."payment_transactions_provider_enum" AS ENUM('STRIPE', 'SEPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."payment_transactions_status_enum" AS ENUM('PENDING', 'SUCCESS', 'FAILED')`);
        await queryRunner.query(`CREATE TABLE "payment_transactions" ("id" uuid NOT NULL, "payment_order_id" uuid NOT NULL, "provider" "public"."payment_transactions_provider_enum" NOT NULL, "provider_transaction_id" character varying(255), "amount" bigint NOT NULL, "currency" character varying(3) NOT NULL, "status" "public"."payment_transactions_status_enum" NOT NULL, "provider_data" jsonb, "paid_at" TIMESTAMP WITH TIME ZONE, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_payment_transactions_provider_transaction" UNIQUE ("provider", "provider_transaction_id"), CONSTRAINT "PK_d32b3c6b0d2c1d22604cbcc8c49" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_payment_transactions_payment_order_id" ON "payment_transactions" ("payment_order_id") `);
        await queryRunner.query(`CREATE TYPE "public"."workspace_subscriptions_provider_enum" AS ENUM('STRIPE', 'SEPAY')`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_subscriptions_status_enum" AS ENUM('PENDING', 'ACTIVE', 'PAST_DUE', 'CANCELED', 'EXPIRED')`);
        await queryRunner.query(`CREATE TABLE "workspace_subscriptions" ("id" uuid NOT NULL, "workspace_id" uuid NOT NULL, "plan_id" uuid NOT NULL, "plan_price_id" uuid, "provider" "public"."workspace_subscriptions_provider_enum", "status" "public"."workspace_subscriptions_status_enum" NOT NULL, "current_period_start" TIMESTAMP WITH TIME ZONE, "current_period_end" TIMESTAMP WITH TIME ZONE, "cancel_at_period_end" boolean NOT NULL DEFAULT false, "canceled_at" TIMESTAMP WITH TIME ZONE, "provider_customer_id" character varying(255), "provider_subscription_id" character varying(255), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_98db3712679ce8ee3435961d85a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_subscriptions_status" ON "workspace_subscriptions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_subscriptions_plan_id" ON "workspace_subscriptions" ("plan_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_workspace_subscriptions_workspace_id" ON "workspace_subscriptions" ("workspace_id") `);
        await queryRunner.query(`ALTER TYPE "public"."teamspace_members_role_name_enum" RENAME TO "teamspace_members_role_name_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."teamspace_members_role_name_enum" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "teamspace_members" ALTER COLUMN "role_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "teamspace_members" ALTER COLUMN "role_name" TYPE "public"."teamspace_members_role_name_enum" USING "role_name"::"text"::"public"."teamspace_members_role_name_enum"`);
        await queryRunner.query(`ALTER TABLE "teamspace_members" ALTER COLUMN "role_name" SET DEFAULT 'MEMBER'`);
        await queryRunner.query(`DROP TYPE "public"."teamspace_members_role_name_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."teamspaces_visibility_enum" RENAME TO "teamspaces_visibility_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."teamspaces_visibility_enum" AS ENUM('OPEN', 'PRIVATE')`);
        await queryRunner.query(`ALTER TABLE "teamspaces" ALTER COLUMN "visibility" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "teamspaces" ALTER COLUMN "visibility" TYPE "public"."teamspaces_visibility_enum" USING "visibility"::"text"::"public"."teamspaces_visibility_enum"`);
        await queryRunner.query(`ALTER TABLE "teamspaces" ALTER COLUMN "visibility" SET DEFAULT 'OPEN'`);
        await queryRunner.query(`DROP TYPE "public"."teamspaces_visibility_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."workspace_members_role_name_enum" RENAME TO "workspace_members_role_name_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_members_role_name_enum" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role_name" TYPE "public"."workspace_members_role_name_enum" USING "role_name"::"text"::"public"."workspace_members_role_name_enum"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role_name" SET DEFAULT 'MEMBER'`);
        await queryRunner.query(`DROP TYPE "public"."workspace_members_role_name_enum_old"`);
        await queryRunner.query(`ALTER TYPE "public"."workspace_invites_role_name_enum" RENAME TO "workspace_invites_role_name_enum_old"`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_role_name_enum" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ALTER COLUMN "role_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ALTER COLUMN "role_name" TYPE "public"."workspace_invites_role_name_enum" USING "role_name"::"text"::"public"."workspace_invites_role_name_enum"`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ALTER COLUMN "role_name" SET DEFAULT 'MEMBER'`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_role_name_enum_old"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."workspace_invites_role_name_enum_old" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ALTER COLUMN "role_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ALTER COLUMN "role_name" TYPE "public"."workspace_invites_role_name_enum_old" USING "role_name"::"text"::"public"."workspace_invites_role_name_enum_old"`);
        await queryRunner.query(`ALTER TABLE "workspace_invites" ALTER COLUMN "role_name" SET DEFAULT 'MEMBER'`);
        await queryRunner.query(`DROP TYPE "public"."workspace_invites_role_name_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."workspace_invites_role_name_enum_old" RENAME TO "workspace_invites_role_name_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."workspace_members_role_name_enum_old" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role_name" TYPE "public"."workspace_members_role_name_enum_old" USING "role_name"::"text"::"public"."workspace_members_role_name_enum_old"`);
        await queryRunner.query(`ALTER TABLE "workspace_members" ALTER COLUMN "role_name" SET DEFAULT 'MEMBER'`);
        await queryRunner.query(`DROP TYPE "public"."workspace_members_role_name_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."workspace_members_role_name_enum_old" RENAME TO "workspace_members_role_name_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."teamspaces_visibility_enum_old" AS ENUM('OPEN', 'PRIVATE')`);
        await queryRunner.query(`ALTER TABLE "teamspaces" ALTER COLUMN "visibility" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "teamspaces" ALTER COLUMN "visibility" TYPE "public"."teamspaces_visibility_enum_old" USING "visibility"::"text"::"public"."teamspaces_visibility_enum_old"`);
        await queryRunner.query(`ALTER TABLE "teamspaces" ALTER COLUMN "visibility" SET DEFAULT 'OPEN'`);
        await queryRunner.query(`DROP TYPE "public"."teamspaces_visibility_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."teamspaces_visibility_enum_old" RENAME TO "teamspaces_visibility_enum"`);
        await queryRunner.query(`CREATE TYPE "public"."teamspace_members_role_name_enum_old" AS ENUM('OWNER', 'MEMBER')`);
        await queryRunner.query(`ALTER TABLE "teamspace_members" ALTER COLUMN "role_name" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "teamspace_members" ALTER COLUMN "role_name" TYPE "public"."teamspace_members_role_name_enum_old" USING "role_name"::"text"::"public"."teamspace_members_role_name_enum_old"`);
        await queryRunner.query(`ALTER TABLE "teamspace_members" ALTER COLUMN "role_name" SET DEFAULT 'MEMBER'`);
        await queryRunner.query(`DROP TYPE "public"."teamspace_members_role_name_enum"`);
        await queryRunner.query(`ALTER TYPE "public"."teamspace_members_role_name_enum_old" RENAME TO "teamspace_members_role_name_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_subscriptions_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_subscriptions_plan_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_workspace_subscriptions_status"`);
        await queryRunner.query(`DROP TABLE "workspace_subscriptions"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_subscriptions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."workspace_subscriptions_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_transactions_payment_order_id"`);
        await queryRunner.query(`DROP TABLE "payment_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_transactions_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_payment_orders_order_code"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_orders_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_payment_orders_status"`);
        await queryRunner.query(`DROP TABLE "payment_orders"`);
        await queryRunner.query(`DROP TYPE "public"."payment_orders_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."payment_orders_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_webhook_events_status"`);
        await queryRunner.query(`DROP TABLE "billing_webhook_events"`);
        await queryRunner.query(`DROP TYPE "public"."billing_webhook_events_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."billing_webhook_events_provider_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_usage_workspace_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_usage_feature_id"`);
        await queryRunner.query(`DROP TABLE "billing_usage"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_billing_plans_code"`);
        await queryRunner.query(`DROP TABLE "billing_plans"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_plan_prices_plan_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_plan_prices_provider"`);
        await queryRunner.query(`DROP TABLE "billing_plan_prices"`);
        await queryRunner.query(`DROP TYPE "public"."billing_plan_prices_provider_enum"`);
        await queryRunner.query(`DROP TYPE "public"."billing_plan_prices_billing_interval_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_plan_features_plan_id"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_billing_plan_features_feature_id"`);
        await queryRunner.query(`DROP TABLE "billing_plan_features"`);
        await queryRunner.query(`DROP INDEX "public"."UQ_billing_features_code"`);
        await queryRunner.query(`DROP TABLE "billing_features"`);
        await queryRunner.query(`DROP TYPE "public"."billing_features_value_type_enum"`);
    }

}
