export enum AiGenerationType {
  WORKSPACE_DRAFT = 'WORKSPACE_DRAFT',
  PROJECT_DRAFT = 'PROJECT_DRAFT',
  TASK_DRAFT = 'TASK_DRAFT',
  WORKSPACE_TREE_DRAFT = 'WORKSPACE_TREE_DRAFT',
  DASHBOARD_INSIGHT = 'DASHBOARD_INSIGHT',
}
