export const ADMIN_TYPES = {
  services: {
    AdminWorkspaceOverviewService: 'AdminWorkspaceOverviewService',
    AdminUpdateWorkspacePlanService: 'AdminUpdateWorkspacePlanService',
    AdminDashboardSummaryService: 'AdminDashboardSummaryService',
    AdminUserGrowthService: 'AdminUserGrowthService',
    AdminWorkspaceGrowthService: 'AdminWorkspaceGrowthService',
    AdminWorkspacePlanService: 'AdminWorkspacePlanService',
    AdminRetentionMetricsService: 'AdminRetentionMetricsService',
    AdminSystemHealthService: 'AdminSystemHealthService',
    AdminRecentActivityService: 'AdminRecentActivityService',
    AdminUserOverviewService: 'AdminUserOverviewService',
  },
  applications: {
    AdminFindAllWorkspaceApplication: 'AdminFindAllWorkspaceApplication',
    AdminWorkspaceOverviewApplication: 'AdminWorkspaceOverviewApplication',
    AdminUpdateWorkspacePlanApplication: 'AdminUpdateWorkspacePlanApplication',
    AdminDashboardSummaryApplication: 'AdminDashboardSummaryApplication',
    AdminUserGrowthApplication: 'AdminUserGrowthApplication',
    AdminWorkspaceGrowthApplication: 'AdminWorkspaceGrowthApplication',
    AdminWorkspacePlanApplication: 'AdminWorkspacePlanApplication',
    AdminRetentionMetricsApplication: 'AdminRetentionMetricsApplication',
    AdminSystemHealthApplication: 'AdminSystemHealthApplication',
    AdminRecentActivityApplication: 'AdminRecentActivityApplication',
    AdminUserOverviewApplication: 'AdminUserOverviewApplication',
  },
  repositories: {
    AdminWorkspaceOverviewRepository: 'AdminWorkspaceOverviewRepository',
    AdminUpdateWorkspacePlanRepository: 'AdminUpdateWorkspacePlanRepository',
    AdminDashboardSummaryRepository: 'AdminDashboardSummaryRepository',
    AdminUserGrowthRepository: 'AdminUserGrowthRepository',
    AdminWorkspaceGrowthRepository: 'AdminWorkspaceGrowthRepository',
    AdminWorkspacePlanRepository: 'AdminWorkspacePlanRepository',
    AdminRetentionMetricsRepository: 'AdminRetentionMetricsRepository',
    AdminSystemHealthRepository: 'AdminSystemHealthRepository',
    AdminRecentActivityRepository: 'AdminRecentActivityRepository',
    AdminUserOverviewRepository: 'AdminUserOverviewRepository',
  },
  uow: {
    UnitOfWork: 'UnitOfWork',
  },
};
