import { PERMISSIONS, PermissionCode } from './permission.constant';
import { WorkspaceRole } from 'src/modules/workspace/domain/enums/workspace-role.enum';

export const ROLE_PERMISSION_MAP: Record<WorkspaceRole, PermissionCode[]> = {
  [WorkspaceRole.OWNER]: Object.values(PERMISSIONS),

  [WorkspaceRole.ADMIN]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,

    PERMISSIONS.WORKSPACE_MEMBER_READ,
    PERMISSIONS.WORKSPACE_MEMBER_ADD,
    PERMISSIONS.WORKSPACE_MEMBER_UPDATE_ROLE,
    PERMISSIONS.WORKSPACE_MEMBER_REMOVE,

    PERMISSIONS.PAGE_CREATE,
    PERMISSIONS.PAGE_READ,
    PERMISSIONS.PAGE_UPDATE,
    PERMISSIONS.PAGE_DELETE,

    PERMISSIONS.PAGE_BLOCK_CREATE,
    PERMISSIONS.PAGE_BLOCK_READ,
    PERMISSIONS.PAGE_BLOCK_UPDATE,
    PERMISSIONS.PAGE_BLOCK_DELETE,

    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ATTACHMENT_DELETE,

    PERMISSIONS.ACTIVITY_READ,
  ],

  [WorkspaceRole.MEMBER]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_MEMBER_READ,

    PERMISSIONS.PAGE_READ,
    PERMISSIONS.PAGE_BLOCK_CREATE,
    PERMISSIONS.PAGE_BLOCK_READ,
    PERMISSIONS.PAGE_BLOCK_UPDATE, // Member có thể sửa block mình tạo
    PERMISSIONS.PAGE_BLOCK_DELETE, // Member có thể xóa block mình tạo

    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ATTACHMENT_DELETE,

    PERMISSIONS.ACTIVITY_READ,
  ],
};
