import {
  PERMISSIONS,
  PermissionCode,
} from 'src/modules/permission/constants/permission.constant';
import { RoleName } from 'src/modules/role/domain/entities/role.entity';

export const ROLE_PERMISSION_MAP: Record<RoleName, PermissionCode[]> = {
  [RoleName.OWNER]: Object.values(PERMISSIONS),

  [RoleName.ADMIN]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_USAGE_READ,

    PERMISSIONS.WORKSPACE_MEMBER_READ,
    PERMISSIONS.WORKSPACE_MEMBER_ADD,
    PERMISSIONS.WORKSPACE_MEMBER_UPDATE_ROLE,
    PERMISSIONS.WORKSPACE_MEMBER_REMOVE,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.BOARD_CREATE,
    PERMISSIONS.BOARD_READ,
    PERMISSIONS.BOARD_UPDATE,
    PERMISSIONS.BOARD_DELETE,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,
    PERMISSIONS.TASK_ASSIGNEE_ADD,
    PERMISSIONS.TASK_ASSIGNEE_REMOVE,

    PERMISSIONS.TASK_COMMENT_CREATE,
    PERMISSIONS.TASK_COMMENT_READ,
    PERMISSIONS.TASK_COMMENT_UPDATE,
    PERMISSIONS.TASK_COMMENT_DELETE,

    PERMISSIONS.SPRINT_CREATE,
    PERMISSIONS.SPRINT_READ,
    PERMISSIONS.SPRINT_UPDATE,
    PERMISSIONS.SPRINT_DELETE,
    PERMISSIONS.SPRINT_START,
    PERMISSIONS.SPRINT_COMPLETE,
    PERMISSIONS.SPRINT_CANCEL,

    PERMISSIONS.PAGE_CREATE,
    PERMISSIONS.PAGE_READ,
    PERMISSIONS.PAGE_UPDATE,
    PERMISSIONS.PAGE_DELETE,

    PERMISSIONS.PAGE_BLOCK_CREATE,
    PERMISSIONS.PAGE_BLOCK_READ,
    PERMISSIONS.PAGE_BLOCK_UPDATE,
    PERMISSIONS.PAGE_BLOCK_DELETE,

    PERMISSIONS.TASK_STATUS_READ,
    PERMISSIONS.TASK_STATUS_MANAGE,
    PERMISSIONS.TASK_PRIORITY_READ,
    PERMISSIONS.TASK_PRIORITY_MANAGE,

    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ATTACHMENT_DELETE,

    PERMISSIONS.ACTIVITY_READ,
  ],

  [RoleName.MEMBER]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_MEMBER_READ,

    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.BOARD_READ,

    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_ASSIGNEE_ADD,
    PERMISSIONS.TASK_ASSIGNEE_REMOVE,

    PERMISSIONS.TASK_COMMENT_CREATE,
    PERMISSIONS.TASK_COMMENT_READ,
    PERMISSIONS.TASK_COMMENT_UPDATE,

    PERMISSIONS.SPRINT_READ,

    PERMISSIONS.PAGE_READ,
    PERMISSIONS.PAGE_BLOCK_READ,
    PERMISSIONS.PAGE_BLOCK_UPDATE,

    PERMISSIONS.TASK_STATUS_READ,
    PERMISSIONS.TASK_PRIORITY_READ,

    PERMISSIONS.ATTACHMENT_UPLOAD,
    PERMISSIONS.ATTACHMENT_READ,

    PERMISSIONS.ACTIVITY_READ,
  ],

  [RoleName.VIEWER]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_MEMBER_READ,

    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.BOARD_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_COMMENT_READ,
    PERMISSIONS.SPRINT_READ,
    PERMISSIONS.PAGE_READ,
    PERMISSIONS.PAGE_BLOCK_READ,
    PERMISSIONS.TASK_STATUS_READ,
    PERMISSIONS.TASK_PRIORITY_READ,
    PERMISSIONS.ATTACHMENT_READ,
    PERMISSIONS.ACTIVITY_READ,
  ],
};
