import { PERMISSIONS } from 'src/modules/permission/constants/permission.constant';
import { RoleName } from 'src/modules/role/domain/entities/role.entity';

export const ROLE_PERMISSION_MAP: Record<RoleName, string[]> = {
  [RoleName.OWNER]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_DELETE,
    PERMISSIONS.WORKSPACE_MANAGE_MEMBERS,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.BOARD_CREATE,
    PERMISSIONS.BOARD_READ,
    PERMISSIONS.BOARD_UPDATE,
    PERMISSIONS.BOARD_DELETE,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,

    PERMISSIONS.ROLE_MANAGE,
  ],

  [RoleName.ADMIN]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.WORKSPACE_UPDATE,
    PERMISSIONS.WORKSPACE_MANAGE_MEMBERS,

    PERMISSIONS.PROJECT_CREATE,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.PROJECT_UPDATE,
    PERMISSIONS.PROJECT_DELETE,

    PERMISSIONS.BOARD_CREATE,
    PERMISSIONS.BOARD_READ,
    PERMISSIONS.BOARD_UPDATE,
    PERMISSIONS.BOARD_DELETE,

    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_UPDATE,
    PERMISSIONS.TASK_DELETE,

    PERMISSIONS.ROLE_MANAGE,
  ],

  [RoleName.MEMBER]: [
    PERMISSIONS.WORKSPACE_READ,
    PERMISSIONS.PROJECT_READ,
    PERMISSIONS.BOARD_READ,
    PERMISSIONS.TASK_READ,
    PERMISSIONS.TASK_CREATE,
    PERMISSIONS.TASK_UPDATE,
  ],
};
