export enum PageBlockType {
  TEXT = 'TEXT',
  HEADER = 'HEADER',
  QUOTE = 'QUOTE',
  DIVIDER = 'DIVIDER',
  CODE = 'CODE',
  TODO = 'TODO',

  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  FILE = 'FILE',
  BOOKMARK = 'BOOKMARK',

  EMBED = 'EMBED',
  FIGMA = 'FIGMA',
  GITHUB_GIST = 'GITHUB_GIST',
  GOOGLE_MAPS = 'GOOGLE_MAPS',
  TWEET = 'TWEET',

  DATABASE_VIEW = 'DATABASE_VIEW',
  TABLE_SIMPLE = 'TABLE_SIMPLE',
  MERMAID = 'MERMAID',
  BUTTON = 'BUTTON',
  TOGGLE = 'TOGGLE',
}
